### ISSUE TITLE
ESP8285 different config

### ISSUE THREAD

**Issue by jon-daemon** [libretuya/esphome-kickstart#12]
I need to flash a few devices with ESP8285 to identify their inputs and outputs.
I added new config files in yaml folder with`board: esp8285` and built the firmware. It seems to work fine but I'm not sure if that was necessary.
Could I just use the ESP8266 firmware?

**Comment by Cossid** [comment]
`esp8285` and `esp01_1m` (default 8266 board) are functionally the same.
The only difference is the 8285 has internal flash instead of external, but that shouldn't matter here.

**Comment by jon-daemon** [comment]
Thanks, so  my separate config is useless.
