### ISSUE TITLE
esphome-kick start on already clout cut device

### ISSUE THREAD

**Issue by mani94321** [libretuya/esphome-kickstart#2]
i have already done cloud cut and have access to device webpage. I want pins layouts and trying to install esphome-kickstart

i tried uploading the uf2 file found at 
https://github.com/libretiny-eu/esphome-kickstart/releases/download/v23.04.28/kickstart-bk7231n-2023-04-28.uf2

but getting error. What i am doing is accessing the web page of the esp device , OTA update > chose file > add uf2 file mentioned at the link. but update is unsuccessful with error 

[W]	[web_server_base:034]	
OTA Update failed! Error: ard=11,uf2=3

can u guide how to install esphome-kickstart on already cloudcut esp device?

**Comment by kuba2k2** [comment]
You're probably flashing the wrong Kickstart image (i.e. you should use BK7231T instead).
